### ISSUE TITLE
POC tracking list

### ISSUE THREAD

**Issue by dannypsnl** [second-state/witc#3]
### checklist

- [x] parse `wit` file 2022/11/28
- [x] check definitions
	- [x] ensure types existed
	- [x] ensure `use` imported file existed 
- [x] generate type definitions
	- [x] record 2022/11/30
	- [x] enum 2022/12/06
	- [x] type alias 2022/12/22
	- [x] variant 2022/12/07
- [x] generate instance import func
- [x] generate runtime export
	- [x] `ImportObject`
	- [x] host functions
- [x] verify generated code will work
	- [x] `string`, and import func works 2022/12/05
	- [x] `record` in instance 2022/12/05
	- [x] `enum` 2022/12/06
	- [x] `list` 2022/12/07
	- [x] `option` 2022/12/06
	- [x] `expected` 2022/12/06
	- [x] `variant` sum of product
- [x] tutorial document

~generate `resource`~
