### ISSUE TITLE
2023 roadmap

### ISSUE THREAD

**Issue by dannypsnl** [second-state/witc#48]
- usage
   - [ ] #75 
- backend targets
   - [x] refactoring Rust
   - [x] generate plugin headers
   - [ ] share IR #77
   - [ ] add C
- better language interface
   - [x] release witc_invoke, witc_abi
- performance issue:
   - [x] make a measurement to be baseline first
   - [x] improve transfer interface, the `write`, `read` only send one byte at once is not the best situation, using buffer will improve the throughput. Refers #82 
- better encoding: we encoded argument and result as bytes to pass over different components, an encoding method which more compact than JSON string would be nice to have
   - NOTE: A potential solution is marking component with its arch & language, if they are same then we don't encode it to JSON but just send the bytes of layout.
   - [ ] linear flattening #89 
- component model
   - [ ] world
   - [ ] interface
   - [ ] package

**Comment by dannypsnl** [comment]
As component model binary goes to have stable release, we will stop this development.
